CompressFiles/Controllers/FileController.cs
using CompressFiles.Models;
using CompressionCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace CompressFiles.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        //public FileController(): base()
        //{
        //    HttpContext.Session.Add("copy", false);
        //    HttpContext.Session.Add("convertion", false);
        //}
        //Modify this controller to make it more reusable and reduce boilerplate code.

        private string serverData()
        {
            return Server.MapPath("~/App_Data");
        }

        private T getSessionData<T>(string key)
        {
            var obj = HttpContext.Session[key];
            if (obj != null) return (T)obj;
            return default(T);
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult FileHandler(HttpPostedFileBase originalFile)
        {
            var fileName = Path.GetFileName(originalFile.FileName);
            var name = Path.Combine(serverData(),fileName);
            originalFile.SaveAs(name);
            originalFile.InputStream.Close(); 
            HttpContext.Session.Add("originalFilename", fileName);
            HttpContext.Session.Add("copy", true);
            return Json("OK");
        }

        public JsonResult Converter()
        {
            if (!Request.IsAjaxRequest() || !getSessionData<bool>("copy"))
            {
                throw new Exception("Invalid Call!");
            }
            var fileName = getSessionData<string>("originalFilename");
            var fullName = Path.Combine(serverData(),fileName);
            var fileStream = new FileStream(fullName,FileMode.Open);
            var output = new FileStream(fullName + ".cf", FileMode.Create);
            var converter = new Compressor(fileStream);
            converter.RunProccess(output);
            HttpContext.Session.Add("convertion", true);

            //Update Db
            if (Request.IsAuthenticated)
            {
                string ID = User.Identity.GetUserId();
                var ac = new ApplicationDbContext();
                ApplicationUser user = ac.Users.FirstOrDefault(x => x.Id == ID);
                var toSave = new UploadedFile();
                toSave.FileName = fileName;
                toSave.OriginalSize = (int)fileStream.Length; //Change to long both o' 'em
                toSave.ConvertedSize = (int)output.Length;
                toSave.DateTime = DateTime.Now;
                toSave.OwnerUser = user;
                ac.AllFiles.Add(toSave);
                //user.Files.Add(toSave);
                ac.SaveChanges();
            }
            output.Close();
            fileStream.Close();
            return Json("OK");
        }

        public FileResult GetConvertedFile()
        {
            if (!getSessionData<bool>("convertion"))
            {
                throw new InvalidOperationException("File hasn't converted yet!");
            }
            var app_data = Server.MapPath("~/App_Data");
            var fileName = (string)HttpContext.Session["originalFilename"];
            var fullName = Path.Combine(app_data, fileName);
            return File(fullName+".cf", "converted", fileName+".cf");
        }
      
        public ActionResult UnCompress(HttpPostedFileBase compressedFile)
        {
            return View();
        }
       

        [HttpPost]
        public JsonResult PostCompressedFile(HttpPostedFileBase compressedFile)
        {
            var fileName = Path.GetFileName(compressedFile.FileName);
            var name = Path.Combine(serverData(), fileName);
            //return Json("Good 'til here");
            compressedFile.SaveAs(name);
            compressedFile.InputStream.Close();
            HttpContext.Session.Add("compressedFilename", fileName);
            HttpContext.Session.Add("copy_compressed", true);
            return Json("OK");
        }

        public JsonResult UnCompressAsync()
        {
            if (!Request.IsAjaxRequest() || !getSessionData<bool>("copy_compressed"))
            {
                throw new Exception("Invalid Call!");
            }
            var fileName = getSessionData<string>("compressedFilename");
            var fullName = Path.Combine(serverData(), fileName);
            var fileStream = new FileStream(fullName, FileMode.Open);
            fullName = fullName.Substring(0, fullName.LastIndexOf('.'));
            var output = new FileStream(fullName, FileMode.Create);
            var converter = new UnCompressor(fileStream);
            converter.RunProccess(output);
            output.Close();
            fileStream.Close();
            HttpContext.Session.Add("convertion_compressed", true);
            return Json("OK");
        }

        public FileResult GetOriginal()
        {
            if (!getSessionData<bool>("convertion_compressed"))
            {
                throw new InvalidOperationException("File hasn't converted yet!");
            }
            var fileName = getSessionData<string>("compressedFilename");
            var fullName = Path.Combine(serverData(), fileName);
            fullName = fullName.Substring(0, fullName.LastIndexOf('.'));
            fileName = fileName.Substring(0, fileName.LastIndexOf('.'));
            return File(fullName, "converted", fileName);
        }

        
    }
}

CompressFiles/Controllers/HomeController.cs
using CompressFiles.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace CompressFiles.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult UnCompress()
        {
            return View();
        }

        //Get the information of the logged user from the log in manager
        public ActionResult Historial()
        {
            string ID = User.Identity.GetUserId();
            var ac = new ApplicationDbContext();
            //var user = ac.Users.FirstOrDefault(x => x.Id == ID);
            var files = from f in ac.AllFiles where f.OwnerUser.Id == ID select f;
            return View(files.ToList());
        }

        public ActionResult GitHub()
        {
            //
            return Redirect("https://github.com/Rogerkael/CompressFiles");
        }
    
    }
}

CompressFiles/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <h2>Hi there!</h2>

        <p>Feel free to download the code, I will share it when I finish, this a site with educational purpose only, best regards.</p>

        <div class="container">
            <div class="row">
                <h4>Current Status:</h4>
                <ul>
                    <li><p>Ready algorithm implementation.</p></li>
                    <li><p>Currently working in the web interface.</p></li>
                    <li><p>For the future : implement mobile application working with web services to this.</p></li>
                </ul>
            </div>
        </div>

        <img class="workmen" src="~/Content/workmen.png" alt="Application under work..still" />


    </div>
</div>

CompressFiles/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <h2>My personal information.</h2>
        <img src="~/Content/me.jpg" alt="me" style="width: 200px; padding: 3px; border: dotted; border-radius: 10px;" />
        <address>
            <dl>
                <dt>
                    Name:
                </dt>
                <dd>
                    Roger Rodriguez Texido
                </dd>
                <dt>
                    Phone:
                </dt>
                <dd>
                    (786) 483-9303
                </dd>
                <dt>
                    Address:
                </dt>
                <dd>
                    616 NW 26 AVE #408, Miami, Fl.
                </dd>
                <dt>Email:</dt>
                <dd>
                    <a href="mailto:roger.rodriguez@mypcusa.com">roger.rodriguez@mypcusa.com</a>
                </dd>
            </dl>
        </address>

        <p class="text-info">This site is brought to you under the <span class="text-danger">Asp.net 4.5 plattaform from Microsoft</span>, the compression algorithm was coded by me.</p>

    </div>
</div>

CompressFiles/Views/Home/Historial.cshtml
@model IEnumerable<CompressFiles.Models.UploadedFile>

@{
    ViewBag.Title = "Historial";
}

<div class="row">

    <div class="col-md-8 col-md-offset-2 historial-table">

        <h2>Your historial in our site</h2>

        @if (Request.IsAuthenticated)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Extension</th>
                        <th>Upload Time</th>
                        <th>Size before</th>
                        <th>Size after</th>
                        <th>Percent(%)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        var percent = (float)@item.ConvertedSize * 100 / (float)@item.OriginalSize;
                        var extension = @item.FileName.Substring(@item.FileName.LastIndexOf("."));
                        percent = 100 - percent;
                        <tr>
                            <th>@item.FileName</th>
                            <th>@extension</th>
                            <th>@item.DateTime</th>
                            <th>@item.OriginalSize Bytes</th>
                            <th>@item.ConvertedSize Bytes</th>
                            <th>@percent</th>
                        </tr>
                    }
                </tbody>
            </table>
        }

        else
        {
            <p class="danger text-danger">You need to log in first.</p>
        }


    </div>
</div>

CompressFiles/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron center-jumbotron">
        <h1>Compress your files</h1>
        <p class="lead">
            Compress one file at the time in our website, with just one click!
        </p>
        <p>We make the reverse operation too!</p>
        <p>
            @*<a href="https://github.com/Rogerkael/CompressFiles" class="btn btn-primary btn-lg" style="white-space: normal" target="_blank">
            See the current code @@ Github.com &raquo;
            </a>*@

            @Html.ActionLink("See the current code @ Github.com »", "GitHub", null, new { @class = "btn btn-primary btn-lg", target = "_blank" })
        </p>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Give us away a file..</h2>
        @using (Html.BeginForm("FileHandler", "File", FormMethod.Post, new { @class = "main-form", enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <label>The file goes right here:</label>
                <input type="file" name="originalFile" id="originalFile" value="" class="form-control" />
            </div>

            <div class="form-group">
                <input id="submit-file" type="submit" name="submit" value="Up Load File!" class="btn btn-primary btn-success form-control" />
            </div>
        }
    </div>
</div>

@section scripts {
        <script src="~/Scripts/indexAjaxHandler.js" type="text/javascript">
            
        </script>
}

CompressFiles/Views/Home/UnCompress.cshtml
@{
    ViewBag.Title = "UnCompress";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Welcome</h1>
        <p class="lead">You want your files back, right?</p>
        <p>We are the other guys, we fix the mistakes and return your files to the original state.</p>
        <p>To begin the reverse process, give us away a compressed file.</p>
        <hr />
        @using (Html.BeginForm("UnCompress", "File", FormMethod.Post, new { @class = "main-form", enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <label>Well..the file first</label>
                <input type="file" name="compressedFile" id="compressedFile" value="" class="form-control" />
            </div>

            <div class="form-group">
                <input id="submit-compressed-file" type="submit" name="submit" value="Upload" class="btn btn-primary btn-success form-control" />
            </div>
        }
    </div>

</div>

@section scripts {
        <script src="~/Scripts/unCompressFileHandler.js"></script>
}